Repository AndcultureCode/AndcultureCode.JavaScript.Core, pull requests merged in 2021-06, with the labels that each got.

#122 Lighten peer dependency versions
  package.json
Labels: bug

#125 handle undefined window in network connection utilities
  src/utilities/network-information-utils.test.ts
  src/utilities/network-information-utils.ts
Labels: bug

#132 Port over Github Actions CI script
  .github/workflows/main.yaml
  .travis.yml
  README.md
Labels: enhancement

#130 Immutable record default values utilities
  package-lock.json
  package.json
  src/constants/auditable-default-values.ts
  src/index.ts
  src/tests/factories/index.ts
  src/tests/factories/stub-resource-record-factory.ts
  src/tests/stubs/stub-resource-record.ts
  src/types/omit-keys.ts
  src/types/required-or-undefined.ts
  src/types/required-or.ts
  src/utilities/do-try.test.ts
  src/utilities/record-utils.test.ts
  src/utilities/record-utils.ts
  src/utilities/scroll-utils.test.ts
  src/utilities/service-utils.test.ts
  tsconfig.dist.json
  tsconfig.json
Labels: dependencies, enhancement

#137 Add ContentLength among other common headers
  src/enumerations/http-header.ts
Labels: enhancement
